### ISSUE TITLE
Values are all lowercased

### ISSUE THREAD

**Issue by gr2m** [stefanbuck/github-issue-parser#1]
Hi Stefan!

I use your action for my automation at https://github.com/gr2m/helpdesk and made another show about it: https://github.com/gr2m/helpdesk/issues/42

One problem I realized is that all values seem to be lowercased. Is that intentional?

**Comment by stefanbuck** [comment]
Good shout. It's kind of intentional, but I can see why this is causing issues. I'm happy to change it or accept a pull request.
