### ISSUE TITLE
JSON output parsed as `{}`

### ISSUE THREAD

**Issue by gr2m** [stefanbuck/github-issue-parser#2]
See this action run. It logs the full event payload and has debugging enabled:

https://github.com/gr2m/helpdesk/runs/3255305558?check_suite_focus=true

I seems as if the values are parsed as part of the title? Maybe the problem is that the line breaks are `\r\n`s instead of just `\n`s?

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/39992/128403512-d6d92c0f-97dd-4501-87b3-d3435a5aaebb.png">

**Comment by stefanbuck** [comment]
Yes, this seems to be related to the windows line breaks. I did not think about different line breaks. I assume this is only the case when you update the issue afterwards. However worth addressing. I'll have a look later this week.
