### ISSUE TITLE
New line spaces and markdown issue templates returning {}

### ISSUE THREAD

**Issue by joshjohanning** [stefanbuck/github-issue-parser#37]
If using this in a private repository, we have to use the markdown issue templates vs. issue forms that's in beta only for public repositories.

If we have a markdown response that doesn't have new lines between the heading and response, it returns as an empty JSON response `{}`. An example of is below:

```md
### Repo name
repo-name

### team
team-name
```

If we ensure that there are spaces before the question/answer, then it works. Like so: 

```md
### Repo name

repo-name

### team

team-name
```

**Comment by stefanbuck** [comment]
Yeah this is a known limitation. Reach out to GitHub and ask them to enable the beta for your org. I'm pretty sure they will.

**Comment by joshjohanning** [comment]
@stefanbuck can’t we maybe parse for a single new line vs 2 new line characters? 

Not sure what your implementation is looking at though.
