### ISSUE TITLE
JSON formatting is failing if some chars are present in form values

### ISSUE THREAD

**Issue by Guts** [stefanbuck/github-issue-parser#38]
To reproduce:

1. create an issue form with a text input
2. create an issue using the form and put some `'` or `()`
3. in your workflow, run `echo '${{ steps.issue-parser.outputs.jsonString }}' > form_submitted.json`

Failed job: https://github.com/TestGTR/website/runs/8229050530?check_suite_focus=true

**Comment by jamacku** [comment]
I had the same problem in one of my [actions](https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/110/files#diff-18c87dbab8b70a5d9848829e4de8a4c858836488e820fc9225bb66b17e0e2e18R112), I have managed to solve it by using `printf %q` for escaping.

Maybe something like this could work, but I didn't test it:

```sh
echo $(printf %q "${{ steps.issue-parser.outputs.jsonString }}") > form_submitted.json
```

**Comment by stefanbuck** [comment]
I'm currently working on v3 with better docs around this issue. For now,  pease take a look at GitHub's [Good practices for mitigating script injection attacks](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks) when using inline scripts. The example blow are safe because it used intermediate environment variable as suggested by GitHub. 

```yaml
- run: echo $JSON_STRING > output.json
  env:
    JSON_STRING: ${{ steps.issue-parser.outputs.jsonString }}
```

**Comment by Guts** [comment]
> I had the same problem in one of my [actions](https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/110/files#diff-18c87dbab8b70a5d9848829e4de8a4c858836488e820fc9225bb66b17e0e2e18R112), I have managed to solve it by using `printf %q` for escaping.
> 
> Maybe something like this could work, but I didn't test it:
> 
> ```shell
> echo $(printf %q "${{ steps.issue-parser.outputs.jsonString }}") > form_submitted.json
> ```

Thanks for your help but it's not working and I'm not good enough with bash and JSON escape logic to work on it efficiently.

> I'm currently working on v3 with better docs around this issue. 

It would be great! If I can avoid dive into jq...

> For now, pease take a look at GitHub's [Good practices for mitigating script injection attacks](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks) when using inline scripts. The example blow are safe because it used intermediate environment variable as suggested by GitHub.

I will

**Comment by Guts** [comment]
> I will

It worked!

- job: https://github.com/geotribu/website/actions/runs/3048476119/jobs/4913580544
- result (sorry in French): https://github.com/geotribu/website/issues/695#issuecomment-1245967485

Thanks!
