### ISSUE TITLE
Blank JSON Response

### ISSUE THREAD

**Issue by GrantBirki** [stefanbuck/github-issue-parser#45]
# Blank JSON Response

Hi there! I have been having one heck of a time getting this Action working. I have made several JS Actions in the past and tried to debug what was going on by forking the repo but [this section](https://github.com/stefanbuck/github-issue-parser/blob/284e5eb74bb2aa3fec17da157e8b184b0ea5a645/index.js#L69-L107) is proving to be quite troublesome.

## The Issue

When running the Action against [this issue template](https://github.com/GrantBirki/actions-sandbox/issues/4), the JSON response in blank.

It should be noted that I am running this Action in a slightly different context. I am running an workflow dispatch model where a person comments `/approve` on an issue that was generated from an issue template. From here, the workflow dispatch feeds the issue body into the Action where it then parses [`issue.body`](https://github.com/stefanbuck/github-issue-parser/blob/main/index.js#L42)

## More Context

At first, I tried modifying the contents of the file present at [`$GITHUB_EVENT_PATH`](https://github.com/stefanbuck/github-issue-parser/blob/main/index.js#L127) to get my `issue.body` content into the Action. This proved to be troublesome, so I just forked the Action and provided a [string as another input option](https://github.com/GrantBirki/issue-template-parser/blob/main/index.js#L147) for the `issue.body`

I also added **a lot** of debug lines to try and troubleshoot why this Action just out the JSON as I would expect.

I even added a *jest* test to my fork of the Action which tests my exact workflow and it seems to work just fine

## Replicating the Issue

The following workflow is where I am experiencing the issue - [link](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112)

1. I get the [issue body](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112#step:3:65) from the workflow dispatch context and pass it into my fork of this Action
2. My fork of the Action [correctly reads in](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112#step:4:6) the issue body and issue template
3. The [id-mapping](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112#step:4:10) looks correct
4. 👀 The [`result`](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112#step:4:11) variable looks pretty botched...
5. The [`json`](https://github.com/GrantBirki/actions-sandbox/actions/runs/3177834833/jobs/5178713112#step:4:12) output is empty 😢 

- [Link to my workflow](https://github.com/GrantBirki/actions-sandbox/blob/b1da5f5935e765dfc28092ec2694c3a333686d70/.github/workflows/approve-dispatch.yml)
- [Link to my fork of the Action](https://github.com/GrantBirki/issue-template-parser/tree/267567dc3ded7291f2e12b4558219f5176cf97e5)
- [Link to my testing issue](https://github.com/GrantBirki/actions-sandbox/issues/4)
- [Link to my issue template](https://github.com/GrantBirki/actions-sandbox/blob/main/.github/ISSUE_TEMPLATE/model_request.yml)

**Comment by stefanbuck** [comment]
Hi @GrantBirki, thanks for this very detailed issue and your time figuring out what is going on here. This is indeed weird, especially the fact that tests are passing. Your change to accept the `issue.body` as an argument made me smile, because this is something I did in the recent [dev](https://github.com/stefanbuck/github-issue-parser/commits/dev) branch which will become the next major version. Unfortunately I don't have much bandwidth to investigate this further due to personal commitments right now. I would suggest trying out the `dev` branch version and hopefully this does just work. If this isn't the case I should be able to put some time aside later this week/early next week to have a closer look.

**Comment by GrantBirki** [comment]
Hey thank you for the replay 😄 

I find it awesome that we both had the exact same approach and even chose identical names for the [input parameter](https://github.com/GrantBirki/issue-template-parser/blob/267567dc3ded7291f2e12b4558219f5176cf97e5/index.js#L147)!

I haven't checked out the dev branch yet but I will give that a spin.

Folks over at @github are working on a volunteer program to help @ersilia-os build out some Actions workflows to help with automation in the open source research space and I'm attempting to adapt this Action for them to solve an [issue here](https://github.com/ersilia-os/ersilia/issues/288). Thanks for your help on this in advance ❤️

**Comment by GrantBirki** [comment]
> If this isn't the case I should be able to put some time aside later this week/early next week to have a closer look

Rather than duplicating your work in a fork, I'll hold off for now and wait to see if the `dev` branch lands and test from there. Thanks!

**Comment by stefanbuck** [comment]
I just released v3. Do you mind giving this another try to see if this issue still exists.

**Comment by GrantBirki** [comment]
Amazing!! I will give this a test tonight and let you know. :crossed_fingers:

**Comment by GrantBirki** [comment]
@stefanbuck Still no success

![image](https://user-images.githubusercontent.com/23362539/197423932-e2dd3e96-2656-4ded-b35c-e07716382503.png)

Link to workflow: https://github.com/GrantBirki/actions-sandbox/actions/runs/3309018642/jobs/5461806379

**Comment by stefanbuck** [comment]
I just spent some time debugging this an here are my observations:

- Passing the body as a hardcoded argument https://github.com/stefanbuck/actions-sandbox/commit/103f01e4ade31113e7ecea4553ac2eba389d06c5 results in the [expected output](https://github.com/stefanbuck/actions-sandbox/actions/runs/3324806335/jobs/5496837242#step:5:15)
- Adding a print statement https://github.com/stefanbuck/actions-sandbox/commit/a0f30c6de12aab9ec2bb5a4e1b3c04de501853dd does print the [expected result](https://github.com/stefanbuck/actions-sandbox/actions/runs/3324816297/jobs/5496860201#step:4:1) 
- It is not a quotation issue https://github.com/stefanbuck/actions-sandbox/commit/d35188e1ea5b4e34de8bceaea1ef1adba3e82038 as the [result is still empty](https://github.com/stefanbuck/actions-sandbox/actions/runs/3324827341/jobs/5496883794#step:6:7)

Something is off when using the set-output command. Maybe worth to isolate / taking apart the action even further which may yields to new findings. Maybe there is a glitch when converting the bash var to an output. Is this something you can inspect further?

**Comment by Lehcar** [comment]
👋 I ran into something similar with testing our own custom parser and I think this was caused by how the issue body was being passed to the parser action. 

> Before the issue body's newlines were being parsed literally (so instead of `\n` being a single character, it was interpreted as a `\` character next to the letter `n`) so the parser was adding extra `\` to escape these characters. 
>
> So,
> ```
> ### Model Name\n\nTest\n\n
> ```
>
> Was being parsed as 
> ```
> " Model Name\\n\\nTest\\n\\n"
> ```
>
> which meant that `(" Model Name\\n\\nTest\\n\\n").split("\n")` returned `" Model Name\\n\\nTest\\n\\n"`. 

I'm not sure if this was _exactly_ the same problem (I didn't really look at the github-issue-parser code 😅 ), but I tested updating how we pass the output [here](https://github.com/GrantBirki/actions-sandbox/compare/main...Lehcar:actions-sandbox:main), in my own fork, and saw that the [issue body was being parsed properly](https://github.com/Lehcar/actions-sandbox/actions/runs/3525896031/jobs/5913172040).

**Comment by GrantBirki** [comment]
Closing as we are now using this fork and it is working ⭐ https://github.com/GrantBirki/issue-template-parser
