### ISSUE TITLE
Question: Why not provide a default value for issue-body in 3.0.0?

### ISSUE THREAD

**Issue by joshjohanning** [stefanbuck/github-issue-parser#46]
https://github.com/stefanbuck/github-issue-parser/releases/tag/v3.0.0

The reasoning for script injection makes sense, but I'm curious as to why not bake `${{ github.event.issue.body }}`  in as a default in the action?

Like:

```diff
  issue-body:
    required: true
    description: 'Issue body to parse'
+   default: ${{ github.event.issue.body }}
```

**Comment by stefanbuck** [comment]
Good shout. Sometimes the most obvious solution is playing hide and seek with the developer trying to get the thing done 🙃 I can made the change tomorrow unless you want to raise a PR for this.

**Comment by joshjohanning** [comment]
@stefanbuck Ha, funny! 😄 

Easy enough, PR raised! #47

**Comment by gr2m** [comment]
smart! This is no longer a breaking change, we could release it as a v2.x feature, too.
