### ISSUE TITLE
Info error at run

### ISSUE THREAD

**Issue by Timmmy-nlb** [stefanbuck/github-issue-parser#58]
Hello,
I have always a error message, but it works as expected:

`Error: Error: ENOENT: no such file or directory, open '.github/ISSUE_TEMPLATE/Bestellung-einer-Benutzeraenderung.yml'`

```steps:
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/Bestellung-einer-Benutzeraenderung.yml # optional but recommended
```

But the template is in the same repo as the workflow and the issue.
Whats wrong?

**Comment by gr2m** [comment]
try running `actions/checkout` beforehand

```yml
      - uses: actions/checkout@v3
```

**Comment by Timmmy-nlb** [comment]
That was the solution, thank you.
