### ISSUE TITLE
Release v3.2.1 is pointing to a commit which it does not belong to any branch on this repository,

### ISSUE THREAD

**Issue by v1v** [stefanbuck/github-issue-parser#82]
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

https://github.com/stefanbuck/github-issue-parser/commit/2d2ff50d4aae06ab58d26bf59468d98086605f11

<img width="1137" alt="image" src="https://github.com/user-attachments/assets/4cdb76bd-e4d1-4ddf-ab70-accc7a1f9a2c" />

**Comment by jamacku** [comment]
@v1v This is the same issue as described in:
- #48

**Comment by stefanbuck** [comment]
Finally fixed
